[project]
name = "griddy-pfr"
version = "0.1.0"
description = "Pro Football Reference SDK for the Griddy platform."
authors = [
    {name = "John Griebel", email = "john@thistlegrow.com"}
]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "griddy-core",
]

[tool.uv.sources]
griddy-core = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/griddy_pfr"]
