[project]
name = "griddy-core"
version = "0.1.0"
description = "Core library for the Griddy SDK â€“ shared HTTP client, exceptions, and base models."
authors = [
    {name = "John Griebel", email = "john@thistlegrow.com"}
]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "requests>=2.28.0",
    "pydantic>=2.0.0",
    "python-dateutil>=2.8.0",
    "pyyaml==6.0.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/griddy_core"]
